name: test
on:
  workflow_dispatch:

jobs:
  generate-art:
    name: generate artifacts
    runs-on: ubuntu-latest

    steps:
      - name: create file
        run: |
          #!/bin/bash

          touch test.txt
      
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: test.txt
      
